server:
  port: 8001
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security
          uri: lb://security
          predicates:
          ## 当请求的路径为gate、rule开头的时，转发到http://localhost:9023服务器上
            - Path=/sec/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

logging:
  logPath: F:\project\git\springCloud\gateway\target\logs
  config: classpath:logback/logback-dev.xml



